# Import the libraries and load the dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('Age vs income.csv')

In [3]:
df.tail()

Age  income(K)
4   23         65
5   21         62
6   25         65
7   30         70
8   31         68

In [4]:
X=df[['Age']]
y=df['income(K)']

# Train test split

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.3, random_state=0)

# Linear Regression

In [20]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()

In [23]:
reg.fit(X_train, y_train)

LinearRegression()

In [24]:
y_train_pred=reg.predict(X_train)

In [25]:
y_train_pred

array([62.91075515, 68.56750572, 64.32494279, 62.20366133, 61.49656751,
       61.49656751])

In [26]:
y_test_pred=reg.predict(X_test)

In [27]:
y_test_pred

array([67.8604119 , 62.20366133, 60.78947368])

In [42]:
reg.predict([[22]])

C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([62.20366133])

# Evaluation 

# r2_score

In [31]:
from sklearn.metrics import r2_score
r2_score(y_train, y_train_pred)

0.8003369628083588

In [41]:
r2_score(y_test, y_test_pred)

0.631840291206576

# MSE 

In [33]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_train, y_train_pred)

np.float64(1.5141113653699463)

In [34]:
mean_squared_error(y_test, y_test_pred)

np.float64(14.317322008633155)

# Using KNN Algorithm

In [43]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor(n_neighbors=3)

In [44]:
knn.fit(X,y)

KNeighborsRegressor(n_neighbors=3)

In [46]:
y_predict_By_knn=knn.predict(X_test)

In [48]:
y_predict_By_knn

array([62.        , 67.66666667, 63.33333333, 60.33333333, 59.        ,
       59.        ])

In [49]:
knn.predict([[22]])

C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([60.33333333])

# Evaluation 

# r2_score

In [51]:
r2_score(y_test, knn.predict(X_test))

0.8152380952380954

# MSE

In [53]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_train, knn.predict(X_train))

np.float64(3.7222222222222197)

In [54]:
mean_squared_error(y_test, knn.predict(X_test))

np.float64(7.185185185185179)